#!/bin/bash
echo "Updating olaris-server from nightlies"
cd /opt
curl -vL 'https://gitlab.com/olaris/olaris-server/-/jobs/artifacts/develop/download?job=build' > /opt/build.zip && unzip -o /opt/build.zip
echo "running olaris-server"
/opt/build/olaris-linux-amd64
